---
---

## Data

### Disclaimers

The following is provided verbatim from the American Statistical Association:

Data provided by Savill's for this DataFest project are not public. These data are proprietary and are only to be used for the purposes of the American Statistical Association’s DataFest. By using this data, you agree to:

1. During participation in ASA's DataFest, store and manage the data securely and privately. This means you may NOT upload the data to websites that may provide access to the data to anyone other than yourselves. (For example, if using Tableau, Github, ChatGPT, make sure privacy settings prevent others from seeing or accessing the data.) If you are not sure, then don't use that service! (Note: Rstudio Cloud does not have access to your data and so you can use it.)

2. Erase all data after your ASA's DataFest participation is complete.

3. Not identify or attempt to identify the information contained in the dataset, nor contact any of the individuals whose information is contained in the dataset.

4. Comply with all applicable U.S. federal and state laws and regulations relating to the maintenance of the dataset, the safeguarding of the confidentiality of the dataset, and the use and disclosure of the dataset.

5. Not publish results of your analysis of the data except that the final products of the competetion (video, slide deck, one-page summary) may be displayed on team members' websites and on campus ASA DataFest websites.

6. Not share the data with anyone who is not a participant of ASA DataFest.

Finally, please do NOT reveal the source of the data or any features of the data to ANYONE before May 3. This will ensure that all ASA DataFest participants around the globe have the same experience with the data as you. This means to not post anything to social media that might reveal clues, and to make sure that public github repositories are not discoverable (and if they are, that identifying work is removed).

### Access

All data files are provided via Google drive: [here](https://drive.google.com/drive/folders/1TMgQTMTkAWM72i2yW8BevfgPlMxIYmMz?usp=drive_link). Note that you must use your Middlebury email address to access this file.  
