---
---

## Schedule

The event will be held at the Q-Center (MBH 202) and will start on April 4th. Notable times are provided below.

### Friday 04/04

- **Opening ceremony**: 6:00 pm - 6:45 pm. Snacks will be provided during the opening ceremony, but it is recommended to have dinner prior to the ceremony. 

- **Work hours**: 6:45 pm - late. Groups are encouraged to stay in Bi Hall and work on their projects. 

### Saturday 04/05

- **Work hours**: 8:00 am - late. Groups are encouraged to stay in Bi Hall and work on their projects. 

### Sunday 04/06

- **Work hours**: 8:00 am - 11:00 am. Groups are encouraged to stay in Bi Hall and work on their projects. 

- **Presentations**: 11:00 am - 12:00 pm. Groups will be given 5 minutes to present their findings to a panel of judges. Locations TBD.

- **Closing ceremony**: 12:15 pm - 12:30 pm. Closing thoughts and awards. 

## Live calendar

The calendar below provides live updates regarding meeting time, food availability, etc. 

<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&ctz=America%2FNew_York&showPrint=0&mode=WEEK&src=bWlkZGRhdGFmZXN0MjAyNUBnbWFpbC5jb20&src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&color=%23039BE5&color=%230B8043" style="border:solid 1px #777" width="100%" height="600" frameborder="0" scrolling="no"></iframe>